// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHrYakGyXPIgV7mQcZa4tnfD9xc0zv0s0',
    appId: '1:939409971323:android:4cfcefe01290451aa5aade',
    messagingSenderId: '939409971323',
    projectId: 'gimnasio-corporesano',
    storageBucket: 'gimnasio-corporesano.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjT7VhaexzZXIVFCgcJ6qyhU3eKrwisxE',
    appId: '1:939409971323:ios:91bc11fc2de2908fa5aade',
    messagingSenderId: '939409971323',
    projectId: 'gimnasio-corporesano',
    storageBucket: 'gimnasio-corporesano.appspot.com',
    iosBundleId: 'com.francogaldame.gimnasiocorporesano',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7G2jTrtnCGn9P7ZL3yl1fPLVd1M4vu1w',
    appId: '1:939409971323:web:926a61a7c07158b4a5aade',
    messagingSenderId: '939409971323',
    projectId: 'gimnasio-corporesano',
    authDomain: 'gimnasio-corporesano.firebaseapp.com',
    storageBucket: 'gimnasio-corporesano.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjT7VhaexzZXIVFCgcJ6qyhU3eKrwisxE',
    appId: '1:939409971323:ios:ecaff6f9bda5f507a5aade',
    messagingSenderId: '939409971323',
    projectId: 'gimnasio-corporesano',
    storageBucket: 'gimnasio-corporesano.appspot.com',
    iosBundleId: 'com.example.gimnasioCorporesano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7G2jTrtnCGn9P7ZL3yl1fPLVd1M4vu1w',
    appId: '1:939409971323:web:98670c83e878687ea5aade',
    messagingSenderId: '939409971323',
    projectId: 'gimnasio-corporesano',
    authDomain: 'gimnasio-corporesano.firebaseapp.com',
    storageBucket: 'gimnasio-corporesano.appspot.com',
  );

}